services:
  mongodb1-example:
    image: mongo:latest
    container_name: mongodb1-example
    ports:
      - "27019:27017"
    environment: #match with image
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "mongo-data1:/data/db" #refer to volume


  mongodb2-example:
    image: mongo:latest
    container_name: mongodb2-example
    ports:
      - "27020:27017"
    environment: #match with image
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: volume 
        source: "mongo-data2"
        target: "/data/db"
        read_only: false

volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2
