#version: "3.8" # no longer used in recent docker compose

services:
  nginx-example:
    container_name: nginx-example
    image: nginx:latest
  nginx-example2:
    container_name: nginx-example2
    image: nginx:latest