services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27019:27017"
    environment: #match with image
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin