services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27019:27017"
    environment: #match with image
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example

  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-example
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: example
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb-example #location name is container mongodb-example
    networks:
      - network_example
    depends_on:
      - mongodb-example

networks:
  network_example:
    name: network_example
    driver: bridge